name: Oracle Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Deployment Script
        run: |
          echo "Running deployment"
          cat database/deploy.sql
